# Uncomment the next line to define a global platform for your project
platform :ios, ’11.0’

target 'baisibudejie-pro' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod “AFNetworking”
pod “SDWebImage”
pod “SVProgressHUD”
pod “pop”
pod “NJKWebViewProgress”
pod “MJExtension”
pod “MJRefresh”
pod “DACircularProgress”

  # Pods for baisibudejie-pro



  target 'baisibudejie-proUITests' do
    inherit! :search_paths
    # Pods for testing

pod “AFNetworking”
pod “SDWebImage”
pod “SVProgressHUD”
pod “pop”
pod “NJKWebViewProgress”
pod “MJExtension”
pod “MJRefresh”
pod “DACircularProgress”
  end

end
